### PR TITLE
Add minor tweaks

### PR DESCRIPTION
**Pull request by trevor-vincent**
**Context:**

The paper got published, so the reference needs updating in the README. The contraction flops calculation that was used in the paper benchmarks is slightly different than the version in the code right now. So this has also been updated to be consistent.

**Description of the Change:**

- Update Readme to with the new reference to the published article.
- Add minor tweak to the contractions flops calculation.

### CODE REVIEW

**Comment by mlxd** [comment]
Changes look fine to me, but not sure why the CI is explicitly failing

**Review by Mandrenkov — APPROVED** [review]
Looks good to me! Thanks for the update. 🎉

Note that we'll need to update some of the tests for the FLOPS change.

**Comment by Mandrenkov** [comment]
Also, do you mind documenting these changes in the changelog?

**Review by mlxd — APPROVED** [review]

**Comment by trevor-vincent** [comment]
Awesome, thanks guys for the comments! I made the necessary changes.

**Pull request merged**
