### PR TITLE
Adopt the Xanadu Sphinx Theme

### PR DESCRIPTION
**Pull request by Mandrenkov**
**Context:**

Currently, all Xanadu OSS projects include their own version of the Xanadu Sphinx theme; however, the [Xanadu Sphinx Theme](https://github.com/XanaduAI/xanadu-sphinx-theme) repository is now publicly available and is the preferred way to access the Xanadu CSS theme and Sphinx directives.

**Description of the Change:**

* Deleted the docs/xanadu_theme directory.
* Updated docs/requirements.txt and docs/conf.py to reference and use the (centralized) Xanadu Sphinx Theme.
* Added a Python 3.10 classifier to setup.py.

**Benefits:**

* The size of this repository is smaller, meaning `git clone` will run faster.
* Updates to the Xanadu Sphinx theme no longer have to be manually ported to this repository.

**Possible Drawbacks:**
None.

**Related GitHub Issues:**
Depends on XanaduAI/xanadu-sphinx-theme#2.

### CODE REVIEW

**Review by doctorperceptron — APPROVED** [review]
Code looks :champagne:. Haven't tested.

**Review by thisac — APPROVED** [review]
Looks good! Attempted to build/test it, but wasn't able to due to the makefile. It seems to be attempting to install `requirements.txt` (using pip) when simply running `make docs`. This might not be such a good idea, since, at least in my case, it will break my environment. 🤔

**Comment by Mandrenkov** [comment]
Thanks for the reviews, @doctorperceptron and @thisac!

> Looks good! Attempted to build/test it, but wasn't able to due to the makefile. It seems to be attempting to install `requirements.txt` (using pip) when simply running `make docs`. This might not be such a good idea, since, at least in my case, it will break my environment. 🤔

Yeah, it also took a few tries for me to build Jet locally. I think we made a mistake by trying to automate too many things in the Makefile since it introduced some assumptions which don't necessarily hold in each environment. That said, I think we should also acknowledge that `make docs` is a complicated process:
1. First, we need to build the Python bindings for the C++ part of Jet.
2. Then, we need to install the Python part of Jet.
3. Finally, we need to generate the Sphinx documentation for _both_ the C++ and Python parts of Jet.

We can usually skip steps (1) and (2) for pure-Python projects but that is not the case here.

**Comment by josh146** [comment]
Flyby comment, and I think this is not high priority at all, but you can set up sphinx to mock out the C++ libraries (I think this is what we did with the walrus back when it included C++) to avoid having to build the bindings

**Comment by Mandrenkov** [comment]
> Flyby comment, and I think this is not high priority at all, but you can set up sphinx to mock out the C++ libraries (I think this is what we did with the walrus back when it included C++) to avoid having to build the bindings.
> 
> The C++ part is still documented via doxygen/exhale/breathe

Thanks for the comment, @josh146! Does the documented C++ part still include the bindings though? It would be a shame to discard that part of the documentation.

**Comment by josh146** [comment]
> Does the documented C++ part still include the bindings though? It would be a shame to discard that part of the documentation.

Ah The Walrus used Cython (not pybind11), so... in retrospect not sure if that has implications here.

**Pull request merged**
